//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio3.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public int Id_domicilio { get; set; }
        public string Direccion { get; set; }
        public string Nombre { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
